name: NewsPet
options:
  deploymentTarget:
    iOS: 14.0
packages:
  UISystem:
    path: LocalPackages/UISystem
  NetworkLayer:
    path: LocalPackages/NetworkLayer
targets:
  NewsPet:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    dependencies:
        - package: UISystem
        - package: NetworkLayer
    sources:
      - path: NewsPet
    settings:
      base:
        BUNDLE_DISPLAY_NAME: "NewsPet"
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: NewsPet/ApplicationLayer/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: NewsPet
      configs:
        Debug:
            SERVER_URL: https://jsonplaceholder.typicode.com
        Release:
            SERVER_URL: https://jsonplaceholder.typicode.com
    info:
        path: NewsPet/ApplicationLayer/Info.plist
        properties:
            CFBundleDisplayName: NewsPet
            CFBundleIconName: Assets.xcassets/AppIcon.appiconset
            CFBundleName: NewsPet
            CFBundleShortVersionString: "1.0"
            CFBundleVersion: "1"
            UIApplicationSceneManifest:
              UIApplicationSupportsMultipleScenes: false
              UISceneConfigurations:
                UIWindowSceneSessionRoleApplication:
                  - UISceneConfigurationName: Default Configuration
                    UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
            UILaunchStoryboardName: LaunchScreen
            ServerUrl: $SERVER_URL
